### ISSUE TITLE
Update theme to use o2r color scheme

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-UI#104]
It would be nice to switch primary and secondary colors for something "more o2r-ish". This might help: https://material-ui.com/customization/theming/

## Buttons, links, clicked links

![image](https://user-images.githubusercontent.com/1325054/74659979-8a455d00-5195-11ea-8094-33d3eaae7798.png)

## Buttons, status colors

![image](https://user-images.githubusercontent.com/1325054/74660011-97624c00-5195-11ea-930a-98e2dd40cdde.png)

## Color suggestions

![image](https://user-images.githubusercontent.com/1325054/74659892-6a159e00-5195-11ea-9c4d-8aae1af7ae4e.png)

**Comment by MarkusKonk** [comment]
@NJaku01 Can you check that? I think the ULB grey would fit

**Comment by NJaku01** [comment]
Of course I can take care of it, the buttons should then be in ifgi-blue or? What exactly should the ulb grey be used for?

**Comment by MarkusKonk** [comment]
We can try out both for the buttons o2r-blue and ulb-grey. Just post two screenshots and then we vote

**Comment by NJaku01** [comment]
## ifgi-blue

![home_blue](https://user-images.githubusercontent.com/46575458/74671326-30e82880-51ab-11ea-99d9-4aee53f72367.png)
![check_blue](https://user-images.githubusercontent.com/46575458/74671336-347baf80-51ab-11ea-9690-62873a564398.png)



## ulb-grey

![home_grey](https://user-images.githubusercontent.com/46575458/74671346-3e051780-51ab-11ea-85ef-11fd642f8066.png)
![check_grey](https://user-images.githubusercontent.com/46575458/74671350-40677180-51ab-11ea-9ff5-7ef810fe90a6.png)

**Comment by nuest** [comment]
@NJaku01 Don't forget the toasters:

![image](https://user-images.githubusercontent.com/1325054/76501921-69de8a80-6443-11ea-8056-f1e49e20a97f.png)

**Comment by MarkusKonk** [comment]
seems done
