### ISSUE TITLE
module not found error

### ISSUE THREAD

**Issue by MarkusKonk** [o2r-project/o2r-UI#11]
After installing a new module with `npm install <module> --save` the platform still cannot find the module.
Try out:
`rm -rf node_modules` and then `npm install`
OR
`docker-compose down -v` and then `sudo docker-compose up`
@NJaku01 Do you have similar issues?

**Comment by NJaku01** [comment]
Yes, I also had this problem some times. With me `sudo docker-compose up --force-recreate` helped.

**Comment by nuest** [comment]
@MarkusKonk We can close this, right?

**Comment by nuest** [comment]
@NJaku01 Please make sure that the developer documentation in the README includes your workaround, then close this.
