### ISSUE TITLE
Upload workspace zip glitch

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-UI#112]
When I drag and drop or select a workspace archive an then click on upload, the "Select file" dialog opens _again_, see (note the already uploaded archive file)

![image](https://user-images.githubusercontent.com/1325054/76498269-d73aed00-643c-11ea-8618-bed99e58be4c.png)

When I close that window and click on "upload" again, then the upload starts.

**Comment by nuest** [comment]
@MarkusKonk Small update: the problem seems to be in Firefox only, in Chrome it works.

**Comment by MarkusKonk** [comment]
@nuest The problem is browser-independent I guess, I have in Chrome, too. The button is too close to the dd area. The focus of the cursor does not change fast enough.

**Comment by MarkusKonk** [comment]
@NJaku01 Can you take a look at that?
