### ISSUE TITLE
Add display and creation of public links

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-UI#118]
The API now has a public link feature, see documentation at https://github.com/o2r-project/api/pull/80

This PR adds this feature to the development environment of the UI: https://github.com/o2r-project/o2r-UI/pull/117

It would be great if _for users of level editor or higher (admin)_:

- [x] the existing public link is displayed on a compendium page (also for the author of ERC)
- [x] if no link exists, one can be added with a button click
- [x] if a link exists, it can be deleted with a button click

**Comment by MarkusKonk** [comment]
I don't get what this is all about.

**Comment by NJaku01** [comment]
I have one more question about this issue. Is the public, if it exists, stored in the metadata or is there another way to get the public link without creating one?

**Comment by nuest** [comment]
The public link is not stored in the metadata directly, but if you're have the high enough user level (Editor) you can get a list of all links at http://localhost/api/v1/link which gives you

```json
{
  "results": [
    {
      "id": "qRfsmEK7uoJAzAL3XGoivCpczeap0UKZ",
      "compendium_id": "WfXza",
      "user": "0000-0002-1701-2564"
    }
  ]
}
```

I agree it would be nice to also get the link for a specific compendium at `.../api/v1/compendium/<compednium_id>/link`, but for now, this only concerns editors/admins and we don't have many links. Noted at https://github.com/o2r-project/api/issues/86

**Comment by NJaku01** [comment]
![image](https://user-images.githubusercontent.com/46575458/98090987-119e4200-1e85-11eb-9564-f3ea25db4899.png)

**Comment by nuest** [comment]
How does it look if the use is not admin?

Also, the content above the text now looks a bit jumbled/disorganised. Please revise! Maybe the public link should be a button, too? Maybe the creation/deletion of the public link should be in a little drop-down that belongs to the button?

**Comment by NJaku01** [comment]
![image](https://user-images.githubusercontent.com/46575458/98368346-7d281100-2037-11eb-947e-27d0f6a9e29e.png)
The Button just disappears if the user is not an admin.

@nuest I have no exact Imagination how the Button should look. I mean, the link is quite long., so it takes a lot of space. Maybe a small Button which is labeled "Share" opens a small Window, which shows the Link and contains the Button to create/delete the link? Of course it is possible to implement a drop-down, but I do not think it looks more organised.

**Comment by nuest** [comment]
Please double check if regular users cannot create public links, see https://o2r.info/api/#tag/Users

Editors or above should be able to do that.

I agree this does not look very nice, but is good enough for this Admin-only feature for now.

_Please open a PR for the code review!_
