### ISSUE TITLE
Comparison view improvements

### ISSUE THREAD

**Issue by MarkusKonk** [o2r-project/o2r-UI#125]
**Synchronize scrolling**

![image](https://user-images.githubusercontent.com/2863409/77302687-fe71a400-6cf1-11ea-9685-a000f4af1786.png)

**Comment by nuest** [comment]
The scrollbar also is "behind" the top layer.

![image](https://user-images.githubusercontent.com/1325054/78156467-22925b00-743f-11ea-8f77-cbfb384b49d7.png)

**Comment by nuest** [comment]
Considering that we take quite a few screenshots from this view, I suggest to move the "CLOSE" button to the top right and keep the o2r logo in the top left corner.

Also, the view wastes a bit of precious screen space, I suggest to recude the space between the columns and above the columns.

**Comment by nuest** [comment]
Can also fix #134 here.

**Comment by nuest** [comment]
@MarkusKonk For the synchronisation of scrolling, maybe you could also have a _common_ table of contents and then jump to the same anchor in the other documents?

1. Hover over a heading
2. An anchor appears
3. User clicks on anchor, and all three windows are scrolled to the same headline
4. (optional) update the permalink in the URL to comparison view and the specific headline?

**Comment by MarkusKonk** [comment]
Almost done. But clicking on the back button of the browser directs users back to the starting page
