### ISSUE TITLE
Improve rendering of log output

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-UI#143]
The rendering of the log output is still quite rough. We can collect some ideas for improvement here:

- highlight specific words or phrases
  - e.g. the "label" log of R Markdown rendering
  - percentages (`24%`), tracking progress
- ... (feel free to edit the list here)

Related to #136

**Comment by NJaku01** [comment]
I have implemented a new display of the logs. 
![Screenshot from 2021-05-21 12-16-10](https://user-images.githubusercontent.com/46575458/119122548-e64d0000-ba2e-11eb-88ea-a8e38d47e63b.png)
@nuest what are your opinions about this?
