### ISSUE TITLE
Show article DOI clearly in the ERC view

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-UI#173]
We used to have this in the old client, and we need it back so that we have an obvious link back to the article for which an ERC is a supplement.

See old PR at https://github.com/o2r-project/o2r-platform/pull/191

This is how it looked like - can of course be more beautiful now, I don't mind:

![image](https://user-images.githubusercontent.com/1325054/93775024-349ccb80-fc22-11ea-9c70-a383ee22c5da.png)

**Comment by nuest** [comment]
@NJaku01 Can you post a screenshot - or does it look exactly like the one above?

**Comment by NJaku01** [comment]
![image](https://user-images.githubusercontent.com/46575458/98091133-43afa400-1e85-11eb-87e5-5a7f3ab462f1.png)

**Comment by nuest** [comment]
Please add the DOI logo again :-)

**Comment by nuest** [comment]
Please open the pull request for the code review.
