### ISSUE TITLE
Add documentation on synced scrolling in result view

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-UI#174]
When I look at the Results comparison (the three HTML files), the synced scrolling only works when I scroll in the leftmost window. Is that correct? If so, there should be a little note (at the bottom or the top) telling the user that.

**Comment by NJaku01** [comment]
This seems to be a problem on Firefox. With Chrome, synchronous scrolling works for all windows as it should.

**Comment by nuest** [comment]
I see. Then a little grey text under the boxes should suffice ("Note that synchronised scrolling in Firefox only works when the curser is placed of the left-most document.").

**Comment by nuest** [comment]
@Fmazin I realise now I've never commited this to the `dev` branch - you've worked on the scrolling, can you please confirm this change is in your codebase or can your merge this?

**Comment by Fmazin** [comment]
The notice for Firefox users is in my code base.

**Comment by nuest** [comment]
Alright. This is included in #191
