### ISSUE TITLE
Re-add "Ship to Zenodo" feature

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-UI#176]
The shipping of completed ERC to Zenodo is currently not supported in the UI.

**This is very important**.

See code in the old platform, which should help to implement this quickly: https://github.com/o2r-project/o2r-platform/search?q=zenodo

- [x] ERC can be published to Zenodo with a click of a Button
- [x] If an ERC was shipped to Zenodo, the Zenodo link is shown in the ERC view
- [x] Test opening of ERC from Zenodo DOIs

**Comment by NJaku01** [comment]
During the shipment of the ERC I get following errors: 
![image](https://user-images.githubusercontent.com/46575458/94993702-2ab88800-0593-11eb-9efd-76cdb64aa7d5.png)

I do not have an idea how to fix it.

**Comment by nuest** [comment]
https://github.com/o2r-project/o2r-shipper/pull/49 was merged an the image was built on Docker Hub.

@NJaku01 Please try locally again with the image `o2rproject/o2r-shipper:e1ce0e6` and let me know if that works. Thanks!

**Comment by NJaku01** [comment]
@nuest Everything new works fine.
