### ISSUE TITLE
Allow disabling of synchronised scrolling in the result view

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-UI#183]
Sometimes, the documents differ to much for the synched scrolling to work. Then the reader should have the option to disable the synching so she can adjust manually.

Example: https://o2r.uni-muenster.de/#/erc/GWME2voTDb5oeaQFuTWMCEMveKS1MiXm

![image](https://user-images.githubusercontent.com/1325054/95275834-e30f5600-0849-11eb-99df-e30c343351d5.png)

**Comment by NJaku01** [comment]
Implementation of the synced scrolling at https://github.com/o2r-project/o2r-UI/blob/master/ui/src/components/erc/Check/Comparison/Comparison.js#L39

**Comment by Fmazin** [comment]
I have implemented a checkbox which disables the sync scrolling if checked. And if it is unchecked the sync scrolling works again. The sync scrolling is still on by default when the result view is entered. 
![Bildschirmfoto von 2020-12-07 16-45-23](https://user-images.githubusercontent.com/48436261/101371954-a5f82c00-38ab-11eb-90fc-bacedd271cdb.png)Screenshot from Opera

This works fine on Opera and Chrome. However on Firefox the initial sync scroll does not work anymore. But if you check uncheck the box it will work. Keep in mind that the sync scroll in firefox does not function fully anyway.

Should i fix this?

**Comment by nuest** [comment]
Yes, it should be fixed. I also find the negative phrasing not so understandable. What do you think about "Synchronise scrolling" with a checked box by default?
