### ISSUE TITLE
Make metadata elements clickable

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-UI#193]
![image](https://user-images.githubusercontent.com/1325054/102093098-0e518b00-3e21-11eb-8c05-501cb67a7b86.png)

All identifiers should be links. Please be aware of https://orcid.org/content/journal-article-display-guidelines and suggest to re-use the DOI logo from the link above the paper, too. We can even use https://spdx.org/licenses/ to derive links to the license texts from the license identifier.

- [x] DOI clickable
- [x] Licenses clickable
- [x] ORCID clickable

**Comment by NJaku01** [comment]
The requested elements are now clickable and the requested website will open in a new tab.
![Screenshot from Metadata](https://user-images.githubusercontent.com/46575458/119230452-8a60a500-bb1c-11eb-92f0-780e4e7ef60c.png)
To get the URL of the Licenses I used the URL which is saved in the [licenses.json](https://github.com/o2r-project/o2r-UI/blob/master/ui/src/helpers/licenses.json)
