### ISSUE TITLE
Add a little warning to the UI if a non-standard license is used

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-UI#195]
Users may define any text for the license field via the metadata of an `Rmd` file. The UI should show a warning, e.g., a orange frame around the license field and a text below it, if a non-standardised license is used.

Related to #93

**Comment by NJaku01** [comment]
This is my current approach:
![Screenshot from 2021-05-21 17-59-53](https://user-images.githubusercontent.com/46575458/119166562-0f858480-ba5f-11eb-9bb1-36579833af4f.png)
