### ISSUE TITLE
Problems with Ubuntu Firefox 86.0 with ERC upload and Binding creation

### ISSUE THREAD

**Issue by Fmazin** [o2r-project/o2r-UI#207]
On this version two problems accrue:

1. The workspaces are uploaded correctly but the user is not correctly directed to the Create ERC page. 
This happens only to some workspaces and the size of the file seems to be the deciding factor.  On the dev build you get this error message.
![Bildschirmfoto von 2021-03-12 15-22-44](https://user-images.githubusercontent.com/48436261/110953343-8a3b7080-8347-11eb-81d7-9297ffec7640.png)

When you do this on the production build the loading Message just stops at 80% and nothing happens. But again you can checkout the the creation page if you enter the link to the creation page. 

![Bildschirmfoto von 2021-03-12 15-49-18](https://user-images.githubusercontent.com/48436261/110956080-8e1cc200-834a-11eb-81ce-67925156d565.png)

In the first case the console displays this error: 

``` Console
Response: Error: Network Error
    createError http://localhost/static/js/1.chunk.js:45678
    handleError http://localhost/static/js/1.chunk.js:45229
``` 

2. When creating a binding you can do all steps except the final add or save parameter operation. The reason for this is that the button does not become clickable.  

![Bildschirmfoto von 2021-03-12 15-54-37](https://user-images.githubusercontent.com/48436261/110956862-5c582b00-834b-11eb-8da6-00bfd044dee3.png)

The issue doesn't come up with Chrome or Opera.

**Comment by Fmazin** [comment]
This might be related to #190.

**Comment by NJaku01** [comment]
I tried to reproduce both errors:

1. I also encountered this problem. For it just happend sometimes, and not always. I got the same error, like @Fmazin. I implemented a further catch, so the website not crush. I do not know why this error occurs.

2.  I could not reproduce this error. For me everything works fine on Ubuntu  Firefox 86.0.

**Comment by Fmazin** [comment]
1. Sounds good.
