### ISSUE TITLE
Add support for config.json file

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-UI#218]
We need a way to configure the server endpoint for the production build, too. So in a way similar to the standalone HTML we discussed for OJS today.

Before the build, we had a `config.json` file, see https://github.com/o2r-project/ansible/blob/master/provisioning/roles/docker-ui/templates/config.json.j2

The values are taken from this configuration file: https://github.com/o2r-project/ansible/blob/master/provisioning/host_vars/ubsvirt148.uni-muenster.de/vars.yml

@NJaku01 @Fmazin Can you please take a look and decide how to proceed? Ideally the values are taken form an external `.json` file that is loaded into `index.html`, because that is easier to configure on the server than replacing a chunk within the HTML file (so what we decided @tnier01 will do for the OJS plugin).

If an external config JSON file is possible, maybe that should also be the way then for OJS?

**Comment by nuest** [comment]
Looks good to me!

**Comment by tnier01** [comment]
So is it then the idea that also the OJS plugin only adjusts the values in the config.js, and this script is then loaded by the HTML, i.e. in the OJS galley?

**Comment by NJaku01** [comment]
Yes, right. In the new build (https://github.com/NJaku01/o2r-UI/releases/download/0.4.0/build.zip) there is a index.html and a config.js. You must include the complete folder and can load the index.html in the OJS galley. You can then adjust the config.js or even replace it completely. However the variables baseUrl, ercURl and title have to be defined.
