### ISSUE TITLE
Deploy UI to demo server

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-UI#57]
For this to work, we need Docker images on DockerHub, and have versioned releases.

- [x] Add automated build `o2rproject/ui` with version tags
- [ ] image works locally (i.e. shows the app)
- [x] Add placeholder to some user-facing HTML page (`App.js`) so the version is transparently visible
- [x] update `post_checkout` hook to set the version in the HTML page
- [x] add `0.2.0` image to reference implementation
- [x] add `0.2.0` image to Ansible deployment configuration
- [x] have _one_ place where API endpoint is configured, currently there are two (@MarkusKonk)
  - https://github.com/o2r-project/o2r-UI/blob/Demo/ui/src/helpers/httpRequests.js#L3
  - https://github.com/o2r-project/o2r-UI/blob/Demo/ui/src/helpers/config.json
- [x] put all into `master` branch (@MarkusKonk)

**Comment by nuest** [comment]
https://cloud.docker.com/u/o2rproject/repository/docker/o2rproject/ui

**Comment by MarkusKonk** [comment]
It's all in the master branch now which is the new demo branch. There is also only one config file now.

**Comment by nuest** [comment]
https://github.com/o2r-project/o2r-UI/pull/100 add the version to the footer

**Comment by nuest** [comment]
https://github.com/o2r-project/ansible/commit/fb9a7d42089ad94f02180989a86590d17d105fa0

**Comment by nuest** [comment]
https://o2r.uni-muenster.de/_config/versions.json

![image](https://user-images.githubusercontent.com/1325054/74548428-241ac900-4f4e-11ea-8c43-d158042ea2e3.png)
