### ISSUE TITLE
Providing too large datasets as download only

### ISSUE THREAD

**Issue by MarkusKonk** [o2r-project/o2r-UI#61]
Some datasets, for example, deaths.csv in tidy data are too large for ou platform. We need to check if a file is larger than, for example, 5mb and if so, only provide it as a download. A message like "This file is too large but you can download it here" should be shown instead.

**Comment by NJaku01** [comment]
I will take care of it soon.

**Comment by NJaku01** [comment]
The result is now in the Branch requiredMetadata
