### ISSUE TITLE
Required Metadata form: affiliation field

### ISSUE THREAD

**Issue by MarkusKonk** [o2r-project/o2r-UI#87]
affiliation is a required field. In case it is empty, it is thus not possible to update the metadata which is currently only visible in the logs.

**Comment by NJaku01** [comment]
@MarkusKonk Is there a way to reproduce the error and where exactly does the error occur in the logs?  I also have a successful metadata update although the field "affiliation" is empty.

**Comment by MarkusKonk** [comment]
No idea what this was about...
