### ISSUE TITLE
Show licenses if available

### ISSUE THREAD

**Issue by MarkusKonk** [o2r-project/o2r-UI#93]
Exampe ERC: INSYDE 
Rmd in workspace has licenses specified but these are not displayed in metadata view. Reason is that the abbreviations in the Rmd do not match the abbreviations in the license list. By default, the metadata view should display whatever is specified in the Rmd. Changes can then be made using the list. 
![image](https://user-images.githubusercontent.com/2863409/74415274-58ee2980-4e43-11ea-9473-b785b2baa97c.png)

**Comment by NJaku01** [comment]
Two licenses have now been added to the [license list](https://github.com/o2r-project/o2r-UI/blob/master/ui/src/helpers/licenses.json). If the ERC was published under a license which is not in the list, this license is now also displayed. However, this license is only selectable for this ERC and only as long as the license is stored in the metadata of the ERC.

**Comment by NJaku01** [comment]
Further enhancements in #195
